# Generated by Django 4.2.4 on 2023-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/foodCategories', verbose_name='تصویر دسته بندی غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/foods', verbose_name='تصویر غذا'),
        ),
    ]
