# Generated by Django 4.2.4 on 2023-08-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0002_foodcategory_image_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(upload_to='images/foodCategories', verbose_name='تصویر دسته بندی غذا'),
        ),
    ]
