# Generated by Django 4.2.4 on 2023-09-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0003_alter_foodcategory_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodGallery',
        ),
    ]
