# Generated by Django 4.2.4 on 2023-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_sitegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitegallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='sitegallery',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
    ]
